In [1]:
# Configuration

# zero-shot, few-shot, chain-of-thought, tree-of-thought
prompting_strategy = "chain-of-thought"
# openai/gpt-5.2, z-ai/glm-5, anthropic/claude-opus-4.5, openai/gpt-oss-120b, z-ai/glm-4.7-flash
model = "anthropic/claude-opus-4.5"
debug = True
root_dir = "../.."

In [2]:
ddl_prompt_path = f"{root_dir}/prompts/{prompting_strategy}/ddl.md"
dml_dql_prompt_path = f"{root_dir}/prompts/{prompting_strategy}/dml-dql.md"
ddl_prompt_template = None
dml_dql_prompt_template = None

with open(ddl_prompt_path) as file:
    ddl_prompt_template = file.read()
with open(dml_dql_prompt_path) as file:
    dml_dql_prompt_template = file.read()

In [3]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
ground_truth_df = pd.read_csv(f"{root_dir}/datasets/validation-set.csv")
ground_truth_df = ground_truth_df.drop(columns=['Comment'])
ground_truth_df.sort_values(by=["Antipattern", "Project", "File", "Line from"], ascending=True, ignore_index=True)

,Project,Antipattern,File,Line from,Line to
0,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/ExchangeConfirmationStatus.java,115,115
1,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Media.java,90,90
2,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,168,168
3,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,183,183
4,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,198,198
5,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Orders.java,93,93
6,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Orders.java,135,135
7,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Orders.java,175,175
8,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Orders.java,240,240
9,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/Annotation.java,133,133
10,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/MasJobRecord.java,65,65
11,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/MasJobRecord.java,100,100
12,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/MasJobRecord.java,110,110
13,juanhaugaard/H2-sakila,31 Flavors,jooq-generated-sakila/src/main/java/org/tayrona/sakila/data/tables/Film.java,126,126
14,ralscha/attic,31 Flavors,travellog/server/src/main/java/ch/rasc/travellog/db/tables/AppUser.java,87,88
15,APSfurizon/fz-backend,Beware of the Unknown,application/src/main/java/net/furizon/backend/feature/fursuits/finder/JooqFursuitFinder.java,88,96
16,APSfurizon/fz-backend,Beware of the Unknown,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Users.java,92,92
17,BluBluBlaBla/vidsummize,Beware of the Unknown,src/main/java/com/vidsummize/jooq/tables/Video.java,77,77
18,MahjongRepository/YagiMotel,Beware of the Unknown,src/main/java/org/yagi/motel/kernel/model/dsl/tables/State.java,59,59
19,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AccessLog.java,81,81
20,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Actor.java,81,81
21,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Application.java,71,71
22,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Application.java,76,76
23,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Application.java,106,106
24,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,66,66
25,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,71,71
26,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,81,81
27,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,101,101
28,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ChangeInitiative.java,115,115
29,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DataTypeUsage.java,74,74
30,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/InvolvementKind.java,76,76
31,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Measurable.java,96,96
32,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/MeasurableCategory.java,81,81
33,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,80,80
34,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,85,85
35,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,95,95
36,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,100,100
37,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,105,105
38,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,110,110
39,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PersonHierarchy.java,69,69
40,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PerspectiveRating.java,75,75
41,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ServerInformation.java,101,101
42,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SourceDataRating.java,85,85
43,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyQuestion.java,80,80
44,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyQuestion.java,100,100
45,hpple/revolut-backend-test,Beware of the Unknown,src/main/java/revolut/backendtest/persistence/jooq/codegen/tables/Accounts.java,70,70
46,hpple/revolut-backend-test,Beware of the Unknown,src/main/java/revolut/backendtest/persistence/jooq/codegen/tables/Accounts.java,75,75
47,hpple/revolut-backend-test,Beware of the Unknown,src/main/java/revolut/backendtest/persistence/jooq/codegen/tables/Transfers.java,80,80
48,ralscha/attic,Beware of the Unknown,travellog/server/src/main/java/ch/rasc/travellog/db/tables/Log.java,107,111
49,tapis-project/tapis-notifications,Beware of the Unknown,tapis-notificationslib/src/main/java/edu/utexas/tacc/tapis/notifications/gen/jooq/tables/Subscriptions.java,126,126
50,wuhunyu/jooq-transaction,Beware of the Unknown,src/main/java/top/wuhunyu/jooq/transaction/codegen/tables/TUser.java,58,58
51,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Authentications.java,77,77
52,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/EmailConfirmationRequest.java,73,73
53,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Events.java,80,80
54,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,78,78
55,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Orders.java,80,80
56,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/ResetPasswordRequests.java,73,73
57,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Roles.java,74,74
58,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Rooms.java,73,73
59,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Sessions.java,71,71
60,BluBluBlaBla/vidsummize,ID Required,src/main/java/com/vidsummize/jooq/tables/Video.java,57,57
61,DiSSCo/dissco-core-annotation-processing-service,ID Required,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/Annotation.java,63,63
62,DiSSCo/dissco-core-annotation-processing-service,ID Required,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/AnnotationBatchRecord.java,57,57
63,DiSSCo/dissco-core-annotation-processing-service,ID Required,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/DigitalSpecimen.java,57,57
64,Macbeth-Klm/Tinkoff-java-course-2024,ID Required,scrapper/src/main/java/edu/java/api/domain/jooq/tables/Chat.java,67,67
65,Macbeth-Klm/Tinkoff-java-course-2024,ID Required,scrapper/src/main/java/edu/java/api/domain/jooq/tables/Link.java,71,71
66,MahjongRepository/YagiMotel,ID Required,src/main/java/org/yagi/motel/kernel/model/dsl/tables/State.java,54,54
67,SleepwalkerPasha/egorov_pa_project,ID Required,scrapper/src/main/java/ru/tinkoff/edu/java/scrapper/domain/jooq/tables/Chat.java,60,60
68,SleepwalkerPasha/egorov_pa_project,ID Required,scrapper/src/main/java/ru/tinkoff/edu/java/scrapper/domain/jooq/tables/Link.java,70,70
69,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AccessLog.java,61,61
70,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Actor.java,61,61
71,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Application.java,61,61
72,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ApplicationGroup.java,61,61
73,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AssessmentDefinition.java,61,61
74,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AttestationInstance.java,61,61
75,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AttestationInstanceRecipient.java,60,60
76,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AttestationRun.java,61,61
77,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Attestation_1_11.java,61,61
78,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AuthoritativeSource.java,60,60
79,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,61,61
80,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ChangeInitiative.java,60,60
81,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ChangeLog.java,61,61
82,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DataType.java,74,74
83,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DatabaseInformation.java,61,61
84,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DrillGridDefinition.java,61,61
85,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EndUserApplication.java,57,57
86,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityAlias.java,59,59
87,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityEnumDefinition.java,60,60
88,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityHierarchy.java,62,62
89,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityNamedNoteType.java,60,60
90,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityStatisticDefinition.java,104,104
91,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityStatisticValue.java,61,61
92,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntitySvgDiagram.java,60,60
93,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityWorkflowDefinition.java,60,60
94,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/FlowDiagram.java,62,62
95,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/InvolvementKind.java,61,61
96,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/LogicalDataElement.java,60,60
97,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/LogicalFlow.java,86,86
98,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Measurable.java,61,61
99,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/MeasurableCategory.java,61,61
100,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/OrganisationalUnit.java,60,60
101,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,60,60
102,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PerspectiveDefinition.java,60,60
103,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalFlow.java,61,61
104,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecDefn.java,61,61
105,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecDefnField.java,61,61
106,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecDefnSampleFile.java,60,60
107,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecification.java,61,61
108,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Process.java,52,52
109,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/RatingScheme.java,60,60
110,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/RatingSchemeItem.java,60,60
111,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Roadmap.java,61,61
112,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Scenario.java,62,62
113,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ScenarioAxisItem.java,60,60
114,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ScenarioRatingItem.java,61,61
115,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ServerInformation.java,61,61
116,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SoftwarePackage.java,60,60
117,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/StaticPanel.java,60,60
118,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyInstance.java,62,62
119,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyInstanceRecipient.java,60,60
120,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyQuestion.java,60,60
121,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyQuestionDropdownEntry.java,60,60
122,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyRun.java,61,61
123,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyTemplate.java,61,61
124,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SvgDiagram.java,60,60
125,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/UserAgentInfo.java,61,61
126,devstronomy/nasa-data-scraper,ID Required,src/main/java/com/devstronomy/jooq/generated/tables/Planet.java,63,63
127,devstronomy/nasa-data-scraper,ID Required,src/main/java/com/devstronomy/jooq/generated/tables/Satellite.java,63,63
128,dndanoff/spring-boot-unit-integration-test-example,ID Required,generated/src/main/java/jooq/com/danoff/demo/db/tables/Employee.java,62,62
129,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/DataFiles.java,56,56
130,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Experiments.java,56,56
131,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Roles.java,54,54
132,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Spreadsheets.java,56,56
133,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Users.java,55,55
134,jiangtj/jc-platform,ID Required,micro-sql-jooq/src/test/java/com/jiangtj/platform/sql/jooq/jooq/tables/SystemOperateRecord.java,47,48
135,jiangtj/jc-platform,ID Required,micro-sql-jooq/src/test/java/com/jiangtj/platform/sql/jooq/jooq/tables/SystemUser.java,43,43
136,jiangtj/jc-platform,ID Required,system-server/src/main/java/com/jiangtj/platform/system/jooq/tables/SystemOperateRecord.java,61,61
137,jiangtj/jc-platform,ID Required,system-server/src/main/java/com/jiangtj/platform/system/jooq/tables/SystemUser.java,56,56
138,ralscha/attic,ID Required,sqrl/demo-server/src/main/java/ch/rasc/sqrldemo/db/tables/AppUser.java,56,57
139,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/AppSession.java,58,59
140,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/AppUser.java,59,60
141,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/Log.java,60,61
142,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/LogPhoto.java,60,61
143,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/Travel.java,59,60
144,ralscha/blog2020,ID Required,hashupgrade/jooq/src/main/java/ch/rasc/hashupgrade/db/tables/AppUser.java,56,57

In [5]:
projects = ground_truth_df["Project"].unique().tolist()
projects

['APSfurizon/fz-backend',
 'BluBluBlaBla/vidsummize',
 'boogiespook/waltz-test',
 'catsloveme/telegram-bot',
 'devstronomy/nasa-data-scraper',
 'DiSSCo/dissco-core-annotation-processing-service',
 'dndanoff/spring-boot-unit-integration-test-example',
 'ebi-gene-expression-group/annotare2',
 'hpple/revolut-backend-test',
 'jiangtj/jc-platform',
 'juanhaugaard/H2-sakila',
 'Macbeth-Klm/Tinkoff-java-course-2024',
 'MahjongRepository/YagiMotel',
 'puzink/Wallet',
 'ralscha/attic',
 'ralscha/blog2020',
 'SleepwalkerPasha/egorov_pa_project',
 'tapis-project/tapis-notifications',
 'therepanic/lapayment-crypto-pay-system',
 'wuhunyu/jooq-transaction']

In [6]:
# Excluding files generated based on system schemas and database extensions/migration tools
excluded_path_fragments = [
    # Java
    'module-info.java',
    'package-info.java',
    
    # MySQL
    'information_schema/InformationSchema.java',
    'information_schema/tables',
    'mysql/Mysql.java',
    'mysql/tables',
    'performance_schema/PerformanceSchema.java',
    'performance_schema/tables',
    'sys/Sys.java',
    'sys/tables',

    # Flyway
    'FlywaySchemaHistory.java',

    # Liquibase
    'Databasechangelog.java',
    'Databasechangeloglock.java',

    # PostgreSQL
    'information_schema/Domains.java',
    'pg_catalog/PgCatalog.java',
    'pg_catalog/tables',

    # Quartz
    'tables/Qrtz',

    # PGP
    'PgpArmorHeaders.java',

    # Dblink
    'tables/Dblink',

    # hstore
    'tables/Each.java',
    'tables/Skeys.java',
    'tables/Svals.java'
]

# Including files that contain a reference to jOOQ or a potential reference to a generated file (the latter may include false positives)
included_phrases = [
    'org.jooq',
    'Tables',
    'tables'
]

# Excluding generated classes, which contain redundant information that doesn't help with detection
excluded_phrases = [
    'extends TableRecordImpl',
    'extends UpdatableRecordImpl',
    'extends org.jooq.impl.UpdatableRecordImpl',
    'extends CatalogImpl',
    'extends SchemaImpl',
    'extends UDTImpl',
    'extends UDTRecordImpl',
    'extends DAOImpl',
    'extends AbstractRoutine',
    'implements EnumType',
    'implements DeserializableJooqEnum',
    'public class Indexes',
    'public class Keys',
    'public class Routines',
    'public class Sequences',
    'public class Tables',
    'public class Domains',
    'class AbstractSpringDAOImpl',
    'extends AbstractSpringDAOImpl',
    'tables.pojos;',
    'tables.interfaces;',
    'Targeted by JavaCPP'
]

ddl_indicator_phrases = [
    'This class is generated by jOOQ',
    'extends TableImpl',
    'extends org.jooq.impl.TableImpl'
]

In [7]:
import glob, os

_keys_cache = {}

def get_project_dir(project: str):
    return f"{root_dir}/repositories/{project.replace("/", "_")}"


def find_all_java_file_paths(project: str):
    return glob.glob(get_project_dir(project) + "/**/*.java", recursive=True)

def find_applicable_file_paths(project: str):
    applicable_file_paths = []
    for file_path in find_all_java_file_paths(project):
        if all(fragment not in file_path for fragment in excluded_path_fragments) and os.path.isfile(file_path):
            with open(file_path, encoding='latin-1') as file:
                file_contents = file.read()
                if any(phrase in file_contents for phrase in included_phrases) and all(phrase not in file_contents for phrase in excluded_phrases):
                    applicable_file_paths.append(file_path)
    return applicable_file_paths


def find_keys_file_paths(project: str):
    # Check if we have already scanned this project for keys
    if project in _keys_cache:
        return _keys_cache[project]

    keys_file_paths = []
    for file_path in find_all_java_file_paths(project):
        if os.path.isfile(file_path):
            try:
                with open(file_path, encoding="latin-1") as file:
                    # Reading only the first few KB is often enough for class declarations
                    # but for safety, we search the whole file once.
                    if "public class Keys " in file.read():
                        keys_file_paths.append(file_path)
            except Exception:
                continue
    
    _keys_cache[project] = keys_file_paths
    return keys_file_paths

def find_closest_keys_file(project: str, file_path: str):
    closest_keys_file_path = None
    closest_common_prefix_length = 0

    for keys_file_path in find_keys_file_paths(project):
        common_prefix_length = len(os.path.commonprefix([file_path, keys_file_path]))
        if common_prefix_length > closest_common_prefix_length:
            closest_keys_file_path = keys_file_path
            closest_common_prefix_length = common_prefix_length
        
    return closest_keys_file_path


def prepare_prompt(project: str, file_path: str):
    with open(file_path) as file:
        lines = file.readlines()
    with open(find_closest_keys_file(project, file_path)) as file:
        keys_lines = file.readlines()

    numbered_contents = "\n".join(
        f"{idx + 1}: {line.strip()}" for idx, line in enumerate(lines)
    )
    keys_file_contents = "\n".join(line.strip() for line in keys_lines)

    is_ddl = any(phrase in numbered_contents for phrase in ddl_indicator_phrases)
    prompt_template = ddl_prompt_template if is_ddl else dml_dql_prompt_template
    prompt_template = prompt_template.replace('FILE_CONTENTS', numbered_contents)
    prompt_template = prompt_template.replace('KEYS_CONTENTS', keys_file_contents)
    return prompt_template

In [8]:
from openai import AsyncOpenAI
import asyncio
from pydantic import BaseModel
from enum import Enum
import json
import time

client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY")
)

class AntipatternName(str, Enum):
    id_required = 'ID Required',
    keyless_entry = 'Keyless Entry',
    rounding_errors = 'Rounding Errors',
    thirty_one_flavors = '31 Flavors',
    poor_mans_search_engine = 'Poor Man’s Search Engine',
    implicit_columns = 'Implicit Columns',
    beware_of_the_unknown = 'Beware of the Unknown'

class AntipatternOccurrence(BaseModel):
    antipatternName: AntipatternName
    linesRangeStart: int
    linesRangeEnd: int
    codeFragment: str
    reasoning: str

class Response(BaseModel):
    chainOfThought: list[str]
    occurrences: list[AntipatternOccurrence]

progress_lock = asyncio.Lock()
processed_count = 0
total_files = sum(len(list(find_applicable_file_paths(p))) for p in projects)
global_input_tokens = 0
global_output_tokens = 0
global_total_tokens = 0
global_total_cost = 0.0
global_retry_count = 0

CONCURRENCY_LIMIT = 10
semaphore = asyncio.Semaphore(CONCURRENCY_LIMIT)

async def generate(project: str, file_path: str):
    global processed_count, global_input_tokens, global_output_tokens, global_total_tokens, global_total_cost, global_retry_count

    while True:
        async with semaphore:
            try:
                prompt = prepare_prompt(project, file_path)
                response = await client.responses.parse(
                    model=model,
                    reasoning={"effort": "none"},
                    temperature=0.0,
                    text_format=Response,
                    input=[{"role": "user", "content": prompt}],
                )

                async with progress_lock:
                    global_input_tokens += response.usage.input_tokens
                    global_output_tokens += response.usage.output_tokens
                    global_total_tokens += response.usage.total_tokens
                    global_total_cost += response.usage.cost
        
                if response.output_parsed == None:
                    async with progress_lock:
                        global_retry_count += 1
                    print(f"Received empty response: {file_path}")
                    print(response)
                    continue
                    
                async with progress_lock:
                    processed_count += 1
                    print(f"[{processed_count}/{total_files}] File analyzed successfully: {file_path}")
        
                return {
                    "project": project,
                    "file": file_path,
                    "response": response.output_parsed,
                    "usage": response.usage,
                    "status": "success"
                }
            except Exception as e:
                async with progress_lock:
                    global_retry_count += 1
                print(f"Exception: {file_path}")
                print(e)

tasks = []

for project in projects:
    for file_path in find_applicable_file_paths(project):
        tasks.append(generate(project, file_path))

start_time = time.perf_counter()
results = await asyncio.gather(*tasks)
end_time = time.perf_counter()

total_runtime = end_time - start_time
success_count = sum(1 for res in results if res["status"] == "success")
error_count = total_files - success_count

print("\n--- Analysis Summary ---")
print(f"Total Runtime:      {total_runtime:.2f} seconds")
print(f"Files Processed:    {success_count} success, {error_count} failed")
print(f"Total Retries:      {global_retry_count}")
print(f"Input Tokens:       {global_input_tokens:,}")
print(f"Output Tokens:      {global_output_tokens:,}")
print(f"Total Tokens:       {global_total_tokens:,}")
print(f"Total Cost:         ${global_total_cost:.6f}")

[1/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/jackson/JsonSerializer.java
[2/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/jackson/SimpleJsonSerializer.java
[3/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/SecurityUtils.java
[4/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/configuration/DatabaseConfiguration.java
[5/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/mapper/JooqUserHasRoleMapper.java
[6/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/session/mapper/JooqSessionMapper.java
[7/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/mapper/JooqRoleMapper.java
[8/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/mapper/JooqPermissionMapper.java
[9/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/media/finder/MediaFinder.java
[10/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/media/action/DeleteMediaActionImpl.java
[11/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/media/action/JooqAddMediaAction.java
[12/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/session/manager/CachedSessionAuthenticationManager.java
[13/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/action/createExchangeConfirmationStatusObj/JooqCreateExchangeObjAction.java
[14/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/finder/JooqPermissionFinder.java
[15/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/media/finder/JooqMediaFinder.java
[16/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/action/deleteExchangeStatusObjAction/JooqDeleteExchangeStatusObjAction.java
[17/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/media/mapper/MediaResponseMapper.java
[18/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/media/mapper/JooqMediaMapper.java
[19/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/action/deleteExpiredExchange/JooqDeleteExpiredExchangesAction.java
[20/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/action/confirmUserExchangeStatus/JooqConfirmUserExchangeStatusAction.java
[21/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/finder/JooqExchangeConfirmationFinder.java
[22/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/mapper/JooqRoomInfoMapper.java
[23/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/mapper/ExchangeConfirmationStatusMapper.java
[24/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/mapper/RoomGuestResponseMapper.java
[25/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/mapper/RoomGuestMapper.java
[26/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/mapper/JooqRoomDataMapper.java
[27/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/mapper/RoomInvitationResponseMapper.java
[28/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/finder/JooqRoomFinder.java
[29/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/action/deleteFursuit/JooqDeleteFursuitAction.java
[30/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/action/updateFursuit/JooqUpdateFursuitAction.java
[31/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/action/bringFursuitToEvent/JooqUpdateBringFursuitToEventAction.java
[32/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/action/createFursuit/JooqCreateFursuitAction.java
[33/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/room/logic/DefaultRoomLogic.java
[34/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/admin/mapper/JooqRoomNotFullRowMapper.java
[35/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/action/setBadge/JooqSetFursuitBadgeAction.java
[36/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/mapper/JooqFursuitDataMapper.java
[37/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/mapper/JooqFursuitDisplayMapper.java
[38/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/action/updateUserLanguage/JooqUpdateUserLanguageAction.java
[39/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/admin/mapper/HotelExportRowMapper.java
[40/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/finder/UserFinder.java
[41/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/action/updateShowInNosecount/JooqUpdateShowInNosecountAction.java
[42/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/authentication/mapper/JooqAuthenticationMapper.java
[43/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/action/setBadge/JooqSetUserBadgeAction.java
[44/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/action/createUser/JooqCreateUserAction.java
[45/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/fursuits/finder/JooqFursuitFinder.java
[46/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/mapper/JooqUserEmailDataMapper.java
[47/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/badge/action/updateUserBadge/JooqUpdateUserBadgeAction.java
[48/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/mapper/JooqUserDisplayMapper.java
[49/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/mapper/JooqSearchUserMapper.java
[50/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/mapper/JooqUserMapper.java
[51/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/badge/mapper/JooqBadgeToPrintMapper.java
[52/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/event/action/update/JooqUpdateEventAction.java
[53/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/event/action/insert/JooqInsertNewEventAction.java
[54/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/badge/finder/JooqBadgeFinder.java
[55/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/event/finder/JooqEventFinder.java
[56/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/user/finder/JooqUserFinder.java
[57/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/event/mapper/JooqEventMapper.java
[58/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/order/action/deleteOrder/JooqDeleteOrderAction.java
[59/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/order/action/updateOrder/JooqUpdateOrderAction.java
[60/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/order/action/upsertOrder/JooqUpsertOrderAction.java
[61/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/markInfoAsUpdated/JooqMarkInfoAsUpdated.java
[62/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/setCardRegistrationStatus/JooqSetCardRegistrationStatus.java
[63/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/order/mapper/JooqOrderMapper.java
[64/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/deleteMembershipCard/JooqDeleteMembershipCardAction.java
[65/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/addMembershipInfo/JooqAddMembershipInfoAction.java
[66/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/updateMembershipOwner/JooqUpdateCardOwner.java
[67/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/pretix/objects/order/finder/JooqOrderFinder.java
[68/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/updateMembershipInfo/JooqUpdateMembershipInfoAction.java
[69/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/shiftEnumerationOfCards/JooqShiftEnumerationOfMembershipCardsAction.java
[70/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/action/createMembershipCard/JooqCreateMembershipCardAction.java
[71/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/mapper/MembershipInfoMapper.java
[72/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/finder/JooqMembershipCardFinder.java
[73/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/finder/JooqPersonalInfoFinder.java
[74/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/mapper/FullInfoMembershipMapper.java
[75/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/removeUsers/JooqRemoveUsersFromRoleAction.java
[76/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/addUsers/JooqAddUsersToRoleAction.java
[77/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/updateRoleInfo/JooqUpdateRoleInfoAction.java
[78/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/deleteRole/JooqDeleteRoleAction.java
[79/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/membership/mapper/MembershipCardMapper.java
[80/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/deletePermissions/JooqDeletePermissionsAction.java
[81/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/addPermissoins/JooqAddPermissionAction.java
[82/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/createRole/JooqCreateRoleAction.java
[83/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/fz-jooq-utils/src/main/java/net/furizon/jooq/DeserializableJooqEnum.java
[84/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/mapper/UserHasRoleMapper.java
[85/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/nosecount/mapper/JooqAdmincountObjMapper.java
[86/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/mapper/ListedRoleMapper.java
[87/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/nosecount/mapper/JooqNosecountObjMapper.java
[88/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/fz-jooq-utils/src/main/java/net/furizon/jooq/strategies/utils/EnumTypeSerializer.java
[89/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/roles/action/updateUserHasRole/JooqUpdateUsersHasRoleAction.java
[90/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/fz-jooq-utils/src/main/java/net/furizon/jooq/strategies/FzGeneratorStrategy.java
[91/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/feature/nosecount/finder/JooqCountFinder.java
[92/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/fz-jooq-utils/src/main/java/net/furizon/jooq/strategies/utils/EnumTypeDeserializer.java
[93/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/infrastructure/JooqOptional.java
[94/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/infrastructure/command/SqlCommand.java
[95/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/infrastructure/command/JooqSqlCommand.java
[96/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/infrastructure/query/SqlQuery.java
[97/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/infrastructure/query/JooqSqlQuery.java
[98/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Fursuits.java
[99/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/ExchangeConfirmationStatus.java
[100/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Rooms.java
[101/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/UserHasRole.java
[102/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/FursuitsOrders.java
[103/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Media.java
[104/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Authentications.java
[105/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipCards.java
[106/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/SchemaMigrations.java
[107/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Sessions.java
[108/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Permission.java
[109/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Users.java
[110/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Roles.java
[111/1159] File analyzed successfully: ../../repositories/APSfurizon_fz-backend/jooq-common/src/main/java/net/furizon/jooq/generated/tables/Events.java

In [12]:
results_df = pd.DataFrame(columns = ["Project", "Antipattern", "File", "Line from", "Line to"])

for result in results:
    if result['status'] == "success":
        for occurrence in result['response'].occurrences:
            results_df.loc[len(results_df)] = {
                "Project": result["project"],
                "Antipattern": occurrence.antipatternName.value,
                "File": result["file"][(len(get_project_dir(result["project"])) + 1):],
                "Line from": occurrence.linesRangeStart,
                "Line to": occurrence.linesRangeEnd
            }
    else:
        print(f"Error: {result['error']}")

results_df.sort_values(by=["Antipattern", "File", "Line from"], ascending=True, ignore_index=True)

,Project,Antipattern,File,Line from,Line to
0,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,168,168
1,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,183,183
2,APSfurizon/fz-backend,31 Flavors,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,198,198
3,juanhaugaard/H2-sakila,31 Flavors,jooq-generated-sakila/src/main/java/org/tayrona/sakila/data/tables/Film.java,126,126
4,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/Annotation.java,133,133
5,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/MasJobRecord.java,65,65
6,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/MasJobRecord.java,100,100
7,DiSSCo/dissco-core-annotation-processing-service,31 Flavors,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/MasJobRecord.java,110,110
8,ralscha/attic,31 Flavors,travellog/server/src/main/java/ch/rasc/travellog/db/tables/AppUser.java,87,88
9,APSfurizon/fz-backend,Beware of the Unknown,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Authentications.java,88,88
10,APSfurizon/fz-backend,Beware of the Unknown,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Users.java,92,92
11,juanhaugaard/H2-sakila,Beware of the Unknown,jooq-generated-sakila/src/main/java/org/tayrona/sakila/data/tables/Address.java,73,73
12,BluBluBlaBla/vidsummize,Beware of the Unknown,src/main/java/com/vidsummize/jooq/tables/Video.java,77,77
13,hpple/revolut-backend-test,Beware of the Unknown,src/main/java/revolut/backendtest/persistence/jooq/codegen/tables/Accounts.java,70,70
14,hpple/revolut-backend-test,Beware of the Unknown,src/main/java/revolut/backendtest/persistence/jooq/codegen/tables/Accounts.java,75,75
15,hpple/revolut-backend-test,Beware of the Unknown,src/main/java/revolut/backendtest/persistence/jooq/codegen/tables/Transfers.java,80,80
16,wuhunyu/jooq-transaction,Beware of the Unknown,src/main/java/top/wuhunyu/jooq/transaction/codegen/tables/TUser.java,58,58
17,tapis-project/tapis-notifications,Beware of the Unknown,tapis-notificationslib/src/main/java/edu/utexas/tacc/tapis/notifications/gen/jooq/tables/Subscriptions.java,126,126
18,ralscha/attic,Beware of the Unknown,travellog/server/src/main/java/ch/rasc/travellog/db/tables/Log.java,107,111
19,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Actor.java,81,81
20,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,101,101
21,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DataTypeUsage.java,74,74
22,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/InvolvementKind.java,76,76
23,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PerspectiveRating.java,75,75
24,boogiespook/waltz-test,Beware of the Unknown,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SourceDataRating.java,85,85
25,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/DataFiles.java,56,56
26,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Experiments.java,56,56
27,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Roles.java,54,54
28,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Spreadsheets.java,56,56
29,ebi-gene-expression-group/annotare2,ID Required,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/jooq/tables/Users.java,55,55
30,dndanoff/spring-boot-unit-integration-test-example,ID Required,generated/src/main/java/jooq/com/danoff/demo/db/tables/Employee.java,62,62
31,ralscha/blog2020,ID Required,hashupgrade/jooq/src/main/java/ch/rasc/hashupgrade/db/tables/AppUser.java,56,57
32,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Events.java,80,80
33,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/MembershipInfo.java,78,78
34,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Orders.java,80,80
35,APSfurizon/fz-backend,ID Required,jooq-common/src/main/java/net/furizon/jooq/generated/tables/Sessions.java,71,71
36,juanhaugaard/H2-sakila,ID Required,jooq-generated-sakila/src/main/java/org/tayrona/sakila/data/tables/Category.java,58,58
37,jiangtj/jc-platform,ID Required,micro-sql-jooq/src/test/java/com/jiangtj/platform/sql/jooq/jooq/tables/SystemOperateRecord.java,47,47
38,jiangtj/jc-platform,ID Required,micro-sql-jooq/src/test/java/com/jiangtj/platform/sql/jooq/jooq/tables/SystemUser.java,43,43
39,Macbeth-Klm/Tinkoff-java-course-2024,ID Required,scrapper/src/main/java/edu/java/api/domain/jooq/tables/Chat.java,67,67
40,Macbeth-Klm/Tinkoff-java-course-2024,ID Required,scrapper/src/main/java/edu/java/api/domain/jooq/tables/Link.java,71,71
41,catsloveme/telegram-bot,ID Required,scrapper/src/main/java/ru/tinkoff/edu/java/scrapper/domain/jooq/tables/Chat.java,51,52
42,SleepwalkerPasha/egorov_pa_project,ID Required,scrapper/src/main/java/ru/tinkoff/edu/java/scrapper/domain/jooq/tables/Chat.java,60,60
43,SleepwalkerPasha/egorov_pa_project,ID Required,scrapper/src/main/java/ru/tinkoff/edu/java/scrapper/domain/jooq/tables/Link.java,70,70
44,catsloveme/telegram-bot,ID Required,scrapper/src/main/java/ru/tinkoff/edu/java/scrapper/domain/jooq/tables/Links.java,60,61
45,ralscha/attic,ID Required,sqrl/demo-server/src/main/java/ch/rasc/sqrldemo/db/tables/AppUser.java,56,57
46,devstronomy/nasa-data-scraper,ID Required,src/main/java/com/devstronomy/jooq/generated/tables/Planet.java,63,63
47,devstronomy/nasa-data-scraper,ID Required,src/main/java/com/devstronomy/jooq/generated/tables/Satellite.java,63,63
48,therepanic/lapayment-crypto-pay-system,ID Required,src/main/java/com/example/jooq/model/tables/Conclusions.java,56,56
49,therepanic/lapayment-crypto-pay-system,ID Required,src/main/java/com/example/jooq/model/tables/Payments.java,56,56
50,therepanic/lapayment-crypto-pay-system,ID Required,src/main/java/com/example/jooq/model/tables/Userfactory.java,56,56
51,therepanic/lapayment-crypto-pay-system,ID Required,src/main/java/com/example/jooq/model/tables/Users.java,56,56
52,BluBluBlaBla/vidsummize,ID Required,src/main/java/com/vidsummize/jooq/tables/Video.java,57,57
53,DiSSCo/dissco-core-annotation-processing-service,ID Required,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/Annotation.java,63,63
54,DiSSCo/dissco-core-annotation-processing-service,ID Required,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/AnnotationBatchRecord.java,57,57
55,DiSSCo/dissco-core-annotation-processing-service,ID Required,src/main/java/eu/dissco/annotationprocessingservice/database/jooq/tables/DigitalSpecimen.java,61,61
56,MahjongRepository/YagiMotel,ID Required,src/main/java/org/yagi/motel/kernel/model/dsl/tables/State.java,54,54
57,wuhunyu/jooq-transaction,ID Required,src/main/java/top/wuhunyu/jooq/transaction/codegen/tables/TUser.java,53,53
58,jiangtj/jc-platform,ID Required,system-server/src/main/java/com/jiangtj/platform/system/jooq/tables/SystemOperateRecord.java,61,61
59,jiangtj/jc-platform,ID Required,system-server/src/main/java/com/jiangtj/platform/system/jooq/tables/SystemUser.java,56,56
60,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/AppSession.java,58,59
61,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/AppUser.java,59,60
62,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/Log.java,60,61
63,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/LogPhoto.java,60,61
64,ralscha/attic,ID Required,travellog/server/src/main/java/ch/rasc/travellog/db/tables/Travel.java,59,60
65,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AccessLog.java,61,61
66,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Actor.java,61,61
67,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Application.java,61,61
68,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ApplicationGroup.java,60,60
69,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AssessmentDefinition.java,61,61
70,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AttestationInstance.java,61,61
71,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AttestationInstanceRecipient.java,60,60
72,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AttestationRun.java,61,61
73,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Attestation_1_11.java,61,61
74,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/AuthoritativeSource.java,60,60
75,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Bookmark.java,61,61
76,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ChangeInitiative.java,60,60
77,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ChangeLog.java,61,61
78,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DataType.java,74,74
79,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DatabaseInformation.java,61,61
80,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/DrillGridDefinition.java,61,61
81,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EndUserApplication.java,57,57
82,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityAlias.java,59,59
83,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityEnumDefinition.java,60,60
84,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityNamedNoteType.java,60,60
85,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityStatisticDefinition.java,104,104
86,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityStatisticValue.java,61,61
87,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntitySvgDiagram.java,60,60
88,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/EntityWorkflowDefinition.java,60,60
89,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/FlowDiagram.java,62,62
90,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/InvolvementKind.java,61,61
91,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/LogicalDataElement.java,60,60
92,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/LogicalFlow.java,86,86
93,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Measurable.java,61,61
94,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/MeasurableCategory.java,61,61
95,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/OrganisationalUnit.java,60,60
96,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Person.java,60,60
97,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PerspectiveDefinition.java,60,60
98,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalFlow.java,61,61
99,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecDefn.java,61,61
100,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecDefnField.java,61,61
101,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecDefnSampleFile.java,60,60
102,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/PhysicalSpecification.java,61,61
103,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Process.java,52,52
104,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/RatingScheme.java,60,60
105,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/RatingSchemeItem.java,60,60
106,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Roadmap.java,61,61
107,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/Scenario.java,62,62
108,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ScenarioAxisItem.java,60,60
109,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ScenarioRatingItem.java,61,61
110,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/ServerInformation.java,61,61
111,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SoftwarePackage.java,60,60
112,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/StaticPanel.java,60,60
113,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyInstance.java,62,62
114,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyInstanceRecipient.java,60,60
115,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyQuestion.java,60,60
116,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyQuestionDropdownEntry.java,60,60
117,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyRun.java,61,61
118,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SurveyTemplate.java,61,61
119,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/SvgDiagram.java,60,60
120,boogiespook/waltz-test,ID Required,waltz-schema/target/generated-sources/jooq/com/khartec/waltz/schema/tables/UserAgentInfo.java,61,61
121,puzink/Wallet,Implicit Columns,SpringJpaJooq/src/main/java/org/wallet/dao/WalletDao.java,27,27
122,puzink/Wallet,Implicit Columns,SpringJpaJooq/src/main/java/org/wallet/dao/WalletDao.java,37,37
123,puzink/Wallet,Implicit Columns,SpringJpaJooq/src/test/java/org/wallet/liquibase/DatabaseMetaDaoImpl.java,25,25
124,ebi-gene-expression-group/annotare2,Implicit Columns,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/SubsTracking.java,144,144
125,ebi-gene-expression-group/annotare2,Implicit Columns,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/SubsTracking.java,279,279
126,ebi-gene-expression-group/annotare2,Implicit Columns,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/SubsTracking.java,297,297
127,ebi-gene-expression-group/annotare2,Implicit Columns,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/SubsTracking.java,316,316
128,ebi-gene-expression-group/annotare2,Implicit Columns,app/integration/ae-subs-tracking/src/main/java/uk/ac/ebi/fg/annotare2/autosubs/SubsTracking.java,432,432
129,APSfurizon/fz-backend,Implicit Columns,application/src/main/java/net/furizon/backend/feature/user/finder/JooqUserFinder.java,298,298
130,ralscha/blog2020,Implicit Columns,hashupgrade/jooq/src/main/java/ch/rasc/hashupgrade/AuthController.java,41,41
131,jiangtj/jc-platform,Implicit Columns,micro-sql-jooq/src/main/java/com/jiangtj/platform/sql/jooq/PageUtils.java,69,69
132,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/AddressGenerator.java,66,66
133,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/AddressGenerator.java,72,72
134,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/AddressGenerator.java,132,132
135,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/AddressGenerator.java,138,138
136,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/FilmGenerator.java,60,60
137,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/FilmGenerator.java,64,64
138,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/FilmGenerator.java,71,71
139,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/FilmGenerator.java,102,102
140,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/FilmGenerator.java,294,294
141,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/FilmGenerator.java,303,303
142,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/StoreGenerator.java,41,41
143,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/StoreGenerator.java,56,56
144,juanhaugaard/H2-sakila,Implicit Columns,sakila-data-generator/src/main/java/org/tayrona/sakila/data/generators/StoreGenerator.java,106,106
145,Macbeth-Klm/Tinkoff-java-course-2024,Implicit Columns,scrapper/src/main/java/edu/java/api/domain/repository/jooq/JooqChatLinkRepository.java,38,38

In [13]:
import pandas as pd
import numpy as np

# --- 1. The Fixed Helper Functions ---

def iou_1d_inclusive(gt, pred):
    """
    Calculates Intersection over Union for DISCRETE inclusive intervals (lines).
    Math: Length = end - start + 1
    """
    # gt and pred are tuples/lists: (start, end)
    
    # 1. Calculate Intersection
    start_inter = max(gt[0], pred[0])
    end_inter = min(gt[1], pred[1])
    
    # We add +1 here because lines are discrete. 
    # If start=79, end=79, overlap is 1 line.
    inter_len = max(0, end_inter - start_inter + 1)
    
    # 2. Calculate Union
    # Union = Area_A + Area_B - Intersection
    len_gt = gt[1] - gt[0] + 1
    len_pred = pred[1] - pred[0] + 1
    
    union_len = len_gt + len_pred - inter_len
    
    return inter_len / union_len if union_len > 0 else 0.0

def calculate_counts(gt_intervals, pred_intervals, threshold=0.5):
    """
    Returns (True Positives for Recall, True Positives for Precision)
    """
    # 1. Calculate Recall Matches (Did we find the GT?)
    tp_recall_count = 0
    for g in gt_intervals:
        # If this GT overlaps sufficiently with ANY prediction
        if any(iou_1d_inclusive(g, p) >= threshold for p in pred_intervals):
            tp_recall_count += 1
            
    # 2. Calculate Precision Matches (Was this Prediction correct?)
    tp_precision_count = 0
    for p in pred_intervals:
        # If this Prediction overlaps sufficiently with ANY GT
        if any(iou_1d_inclusive(g, p) >= threshold for g in gt_intervals):
            tp_precision_count += 1
            
    return tp_recall_count, tp_precision_count

# --- 2. Data Preparation ---

# Ensure strict types
ground_truth_df['Line from'] = ground_truth_df['Line from'].astype(int)
ground_truth_df['Line to'] = ground_truth_df['Line to'].astype(int)
results_df['Line from'] = results_df['Line from'].astype(int)
results_df['Line to'] = results_df['Line to'].astype(int)

# Strip whitespace from string columns just in case
ground_truth_df['File'] = ground_truth_df['File'].str.strip()
results_df['File'] = results_df['File'].str.strip()
ground_truth_df['Project'] = ground_truth_df['Project'].str.strip()
results_df['Project'] = results_df['Project'].str.strip()

# --- 3. Metric Calculation ---

all_antipatterns = set(ground_truth_df['Antipattern']).union(set(results_df['Antipattern']))
metric_rows = []

for ap in all_antipatterns:
    # Filter Dataframes by Antipattern first
    gt_subset = ground_truth_df[ground_truth_df['Antipattern'] == ap]
    pred_subset = results_df[results_df['Antipattern'] == ap]
    
    # Get all unique (Project, File) combinations
    # We use tuples to ensure we match strictly on both
    gt_keys = set(zip(gt_subset['Project'], gt_subset['File']))
    pred_keys = set(zip(pred_subset['Project'], pred_subset['File']))
    relevant_keys = gt_keys.union(pred_keys)
    
    ap_tp_recall = 0   
    ap_tp_precision = 0 
    ap_total_gt = 0    
    ap_total_pred = 0  
    
    for (proj, filename) in relevant_keys:
        # Extract intervals where BOTH Project and File match
        gts = gt_subset[
            (gt_subset['Project'] == proj) & 
            (gt_subset['File'] == filename)
        ][['Line from', 'Line to']].values.tolist()
        
        preds = pred_subset[
            (pred_subset['Project'] == proj) & 
            (pred_subset['File'] == filename)
        ][['Line from', 'Line to']].values.tolist()
        
        ap_total_gt += len(gts)
        ap_total_pred += len(preds)
        
        # Calculate Matches using the Inclusive IoU
        matches_rec, matches_prec = calculate_counts(gts, preds, threshold=0.5)
        
        ap_tp_recall += matches_rec
        ap_tp_precision += matches_prec

    # Calculate Rates
    precision = ap_tp_precision / ap_total_pred if ap_total_pred > 0 else 0.0
    recall = ap_tp_recall / ap_total_gt if ap_total_gt > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
        
    metric_rows.append({
        "Antipattern": ap,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1,
        "Support (GT Count)": ap_total_gt,
        "Pred Count": ap_total_pred
    })

# --- 4. Weighted Average and Output ---

metrics_df = pd.DataFrame(metric_rows)
total_support = metrics_df["Support (GT Count)"].sum()

if total_support > 0:
    w_avg_prec = (metrics_df["Precision"] * metrics_df["Support (GT Count)"]).sum() / total_support
    w_avg_rec = (metrics_df["Recall"] * metrics_df["Support (GT Count)"]).sum() / total_support
    w_avg_f1 = (metrics_df["F1-Score"] * metrics_df["Support (GT Count)"]).sum() / total_support
else:
    w_avg_prec, w_avg_rec, w_avg_f1 = 0.0, 0.0, 0.0

metrics_df.loc[len(metrics_df)] = {
    "Antipattern": "WEIGHTED AVERAGE",
    "Precision": w_avg_prec,
    "Recall": w_avg_rec,
    "F1-Score": w_avg_f1,
    "Support (GT Count)": total_support,
    "Pred Count": metrics_df["Pred Count"].sum()
}

# Display
metrics_df.round(4)

,Antipattern,Precision,Recall,F1-Score,Support (GT Count),Pred Count
0,Implicit Columns,0.9650,0.9486,0.9567,350,343
1,Rounding Errors,1.0000,1.0000,1.0000,10,10
2,Poor Man’s Search Engine,0.5789,0.8000,0.6718,15,19
3,Keyless Entry,0.7237,0.9821,0.8333,56,76
4,31 Flavors,1.0000,0.6000,0.7500,15,9
5,ID Required,0.9479,0.9192,0.9333,99,96
6,Beware of the Unknown,0.8750,0.3889,0.5385,36,16
7,WEIGHTED AVERAGE,0.9248,0.9002,0.9030,581,569

In [14]:
results

[{'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/jackson/SimpleJsonSerializer.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL query antipatterns.', "Looking at the class, it's a `SimpleJsonSerializer` that implements `JsonSerializer`.", "The class uses Jackson's `ObjectMapper` to serialize objects to JSON strings.", 'It has two methods: `serializeAsString` and `serializeAsJson`.', 'The `serializeAsJson` method uses `JSON.valueOf()` which is a jOOQ JSON type, but this is just creating a JSON value, not querying the database.', 'This class does not contain any jOOQ DSL queries or DAO interactions.', 'There are no SELECT statements, no LIKE/ILIKE patterns, no column selections, and no NULL handling in query logic.', 'This is purely a utility class for JSON serialization, not database interaction.', 'No antipatterns are present in this code.'], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1354, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=203, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1557, cost=0.011845, is_byok=False, cost_details={'upstream_inference_cost': 0.011845, 'upstream_inference_input_cost': 0.00677, 'upstream_inference_output_cost': 0.005075}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/jackson/JsonSerializer.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL query antipatterns.', "Looking at the class, it's an interface called `JsonSerializer` with two method declarations.", 'The interface has two methods: `serializeAsString` and `serializeAsJson`.', "This interface doesn't contain any actual implementation code - it only declares method signatures.", 'There are no jOOQ DSL operations, no SQL queries, no LIKE/ILIKE patterns, no column selections, and no NULL handling logic.', 'The `org.jooq.JSON` import is just a type reference for the return type of one method.', 'Since this is just an interface definition with no implementation, there are no antipatterns to report.'], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1144, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=170, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1314, cost=0.00997, is_byok=False, cost_details={'upstream_inference_cost': 0.00997, 'upstream_inference_input_cost': 0.00572, 'upstream_inference_output_cost': 0.00425}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/SecurityUtils.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL query antipatterns.', "Looking at the class, it's called SecurityUtils and contains utility methods for security-related operations.", 'The class imports from net.furizon.jooq.generated.tables.Sessions, which is a jOOQ generated table.', 'However, the only usage of jOOQ in this class is on line 9: `Sessions.SESSIONS.CREATED_BY_IP_ADDRESS.getDataType().length()`', 'This is simply accessing metadata about a column (getting the data type length), not executing any SQL query.', 'There is no DSL context usage, no query building, no fetching of data, no LIKE/ILIKE operations, no SELECT statements.', 'The class is purely a utility for extracting IP addresses from HTTP requests, using the jOOQ table definition only to get the maximum allowed length for an IP address field.', 'Since there are no actual SQL queries being built or executed in this class, there are no antipatterns to report.'], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1402, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=242, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1644, cost=0.01306, is_byok=False, cost_details={'upstream_inference_cost': 0.01306, 'upstream_inference_input_cost': 0.00701, 'upstream_inference_output_cost': 0.00605}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/finder/JooqPermissionFinder.java',
  'response': Response(chainOfThought=["I need to analyze this Java class for SQL antipatterns: Poor Man's Search Engine, Implicit Columns, and Beware of the Unknown.", 'Let me go through each method and check for these antipatterns:', "1. Poor Man's Search Engine - Looking for LIKE, ILIKE, or regex usage for full-text search. I don't see any LIKE, ILIKE, or regex patterns in this code. All queries use exact equality comparisons (.eq()).", '2. Implicit Columns - Looking for queries that fetch all columns from a table (SELECT *) or fetch into records/DAOs without specifying columns. Let me check each query:', '- getUserPermissions (line 46-57): Selects only PERMISSION.PERMISSION_VALUE - specific column', '- getPermissionsFromRoleId (line 62-65): Uses selectPermission() which selects PERMISSION.PERMISSION_VALUE and PERMISSION.ROLE_ID - specific columns', '- getPermissionsFromRoleInternalName (line 70-77): Uses selectPermission() - specific columns', '- getRoleFromId (line 82-85): Uses selectRole() which selects specific columns from ROLES', '- getRoleFromInternalName (line 90-93): Uses selectRole() - specific columns', '- getRolesFromUserId (line 98-105): Uses selectRole() - specific columns', '- getUsersWithRoleInternalName (line 110-119): Selects only USER_HAS_ROLE.USER_ID - specific column', '- getUsersWithRoleId (line 124-129): Selects only USER_HAS_ROLE.USER_ID - specific column', '- getDisplayUsersWithRoleId (line 134-153): Selects specific columns from USERS, MEDIA, USER_HAS_ROLE', '- getUserHasRoleByRoleId (line 158-166): Selects specific columns from USER_HAS_ROLE', '- getUsersWithPermission (line 171-182): Selects only USER_HAS_ROLE.USER_ID - specific column', '- userHasRole methods (line 186-212): Select only USER_HAS_ROLE.USER_ID - specific column', '- userHasPermission (line 216-228): Selects only USER_HAS_ROLE.USER_ID - specific column', '- listPermissions (line 232-302): Selects specific columns from ROLES and computed fields', '- selectPermission() helper (line 306-310): Selects specific columns', '- selectRole() helper (line 313-320): Selects specific columns', 'All queries explicitly specify which columns to select, so no Implicit Columns antipattern.', '3. Beware of the Unknown - Looking for NULLABLE columns used in query logic that could produce incorrect results with NULL. I need to check for conditions on nullable columns, especially in WHERE clauses or JOIN conditions.', 'Looking at the queries, I see LEFT JOINs being used (e.g., line 151-152, 292-295), but these are handled appropriately with COALESCE for the nullable results.', 'In line 239: USER_HAS_ROLE.TEMP_EVENT_ID.isNotNull() - this is checking for NULL explicitly, which is correct usage.', "I don't see any obvious cases where nullable columns are used in equality comparisons or other logic that would produce incorrect results with NULL values.", "After thorough analysis, I don't find any of the specified antipatterns in this code."], occurrences=[]),
  'usage': ResponseUsage(input_tokens=5388, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=816, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=6204, cost=0.04734, is_byok=False, cost_details={'upstream_inference_cost': 0.04734, 'upstream_inference_input_cost': 0.02694, 'upstream_inference_output_cost': 0.0204}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/mapper/JooqPermissionMapper.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL query antipatterns.', "Looking at the class, it's a mapper class called JooqPermissionMapper that maps a jOOQ Record to a JooqPermission DTO.", 'The class imports from net.furizon.jooq.generated.Tables.PERMISSION, which is a jOOQ generated table.', 'In the map method, it extracts specific columns from the record: PERMISSION.PERMISSION_VALUE (line 15) and PERMISSION.ROLE_ID (line 24).', 'Let me check for each antipattern:', "1. Poor Man's Search Engine: There's no LIKE, ILIKE, or regex usage in this class. No issue here.", "2. Implicit Columns: This class only reads specific columns from a Record that was passed in. It doesn't create any queries itself - it just maps an existing Record. The actual query that created this Record is not in this class. So there's no 'SELECT *' or fetchAll pattern here. No issue.", "3. Beware of the Unknown: The code accesses PERMISSION.PERMISSION_VALUE and PERMISSION.ROLE_ID. I don't have information about whether these columns are NULLABLE. The code does check if permission is null after calling Permission.get(), but that's Java null-handling, not SQL NULL handling. There's no query logic here that would produce incorrect results with NULL - this is just a mapper that reads values from a record. No issue.", "This class is a mapper that processes already-fetched records. It doesn't construct queries, so there are no SQL antipatterns to report."], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1359, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=378, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1737, cost=0.016245, is_byok=False, cost_details={'upstream_inference_cost': 0.016245, 'upstream_inference_input_cost': 0.006795, 'upstream_inference_output_cost': 0.00945}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/mapper/JooqRoleMapper.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL query antipatterns.', "Looking at the class, it's a mapper class called JooqRoleMapper that maps a jOOQ Record to a Role object.", 'The map method takes a Record and extracts specific columns from it using record.get() with explicit column references (ROLES.ROLE_ID, ROLES.DISPLAY_NAME, etc.).', 'Let me check for each antipattern:', "1. Poor Man's Search Engine: There's no LIKE, ILIKE, or regex usage in this code. No issue here.", "2. Implicit Columns: This mapper doesn't perform any query itself - it just maps an already-fetched Record. The mapper explicitly accesses specific columns (ROLE_ID, DISPLAY_NAME, INTERNAL_NAME, ROLE_ADMINCOUNT_PRIORITY, SHOW_IN_NOSECOUNT). This is not a case of fetching all columns - it's just reading specific fields from a Record that was passed in. The antipattern would be in the code that creates the query and fetches the Record, not in this mapper.", "3. Beware of the Unknown: There's no query logic here that could produce incorrect results with NULL values. This is just a mapper that reads values from a Record.", "This class is just a utility mapper and doesn't contain any of the antipatterns I'm looking for. The actual query that fetches the data would be elsewhere."], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1255, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=336, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1591, cost=0.014675, is_byok=False, cost_details={'upstream_inference_cost': 0.014675, 'upstream_inference_input_cost': 0.006275, 'upstream_inference_output_cost': 0.0084}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/permissions/mapper/JooqUserHasRoleMapper.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL antipatterns related to jOOQ usage.', "Looking at the class, it's a mapper class called JooqUserHasRoleMapper that maps a jOOQ Record to a JooqUserHasRole DTO.", 'The map method takes a Record and extracts specific columns: USER_HAS_ROLE.USER_ID, USER_HAS_ROLE.ROLE_ID, and USER_HAS_ROLE.TEMP_EVENT_ID.', 'Let me check for each antipattern:', "1. Poor Man's Search Engine: There's no LIKE, ILIKE, or regex usage in this code. No issue here.", "2. Implicit Columns: The code is extracting specific columns from a Record using explicit column references (USER_HAS_ROLE.USER_ID, etc.). This is not selecting all columns - it's just reading specific fields from an already-fetched record. The mapper itself doesn't perform any query or fetch operation. No issue here.", "3. Beware of the Unknown: There's no query logic here that could produce incorrect results with NULL values. The code is simply mapping record fields to a DTO. No issue here.", "This class is just a mapper that extracts specific columns from a Record. It doesn't contain any of the antipatterns I'm looking for."], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1259, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=319, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1578, cost=0.01427, is_byok=False, cost_details={'upstream_inference_cost': 0.01427, 'upstream_inference_input_cost': 0.006295, 'upstream_inference_output_cost': 0.007975}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/session/manager/CachedSessionAuthenticationManager.java',
  'response': Response(chainOfThought=["I need to analyze this Java class for SQL antipatterns: Poor Man's Search Engine, Implicit Columns, and Beware of the Unknown.", 'Let me go through the code systematically:', "1. Poor Man's Search Engine - Looking for LIKE, ILIKE, or regex patterns used for full-text search. I see `equalIgnoreCase` on line 236, but this is not LIKE/ILIKE - it's just a case-insensitive equality check. No LIKE or regex patterns found.", '2. Implicit Columns - Looking for SELECT * or fetching all columns from a table. I need to check if any queries fetch all columns without explicit column selection. Looking through the code:', '- Lines 162-174: Explicit column selection for SESSIONS', '- Lines 179-182: Explicit column selection (SESSIONS.ID)', '- Lines 189-216: Explicit column selection for multiple tables', '- Lines 234-237: Uses selectAuthentication() which has explicit columns (lines 254-264)', '- Lines 245-248: Uses selectAuthentication() which has explicit columns', '- Lines 269-282: Explicit column insertion', '- Lines 284-294: Explicit column insertion', '- Lines 300-304: Explicit column selection', '- Lines 309-314: Explicit column selection', '- Lines 325-329: Explicit column update', '- Lines 335-339: Explicit column update', '- Lines 347-355: Explicit column selection', '- Lines 361-369: Explicit column update', '- Lines 374-382: Explicit column selection', '- Lines 386-389: Explicit deletion', '- Lines 393-398: Explicit column selection', '- Lines 402-406: Explicit column selection', '- Lines 411-415: Explicit column selection', '- Lines 421-430: Explicit column insertion', '- Lines 435-440: Explicit column update', '- Lines 445-450: Explicit column update', '- Lines 457-467: Explicit column selection in subquery', '- Lines 473-476: Explicit deletion', '- Lines 480-484: Explicit column selection', 'All queries appear to have explicit column selections. No Implicit Columns antipattern found.', "3. Beware of the Unknown - Looking for NULLABLE columns used in query logic that could produce incorrect results with NULL. I need to check for conditions on nullable columns that don't handle NULL properly.", 'Looking at the queries:', '- Line 212: `AUTHENTICATIONS.AUTHENTICATION_EMAIL_VERIFICATION_CREATION.isNull()` - This is actually proper NULL handling', '- Line 463: `AUTHENTICATIONS.AUTHENTICATION_EMAIL_VERIFICATION_CREATION.isNotNull()` - This is proper NULL handling', "- Line 464: `AUTHENTICATIONS.AUTHENTICATION_EMAIL_VERIFICATION_CREATION.lessThan(deleteFrom)` - This is used after isNotNull() check, so it's fine", "I don't see any obvious cases where nullable columns are used in a way that would produce incorrect results due to NULL values. The code properly uses isNull() and isNotNull() checks where needed.", "After thorough analysis, I don't find any of the specified antipatterns in this code."], occurrences=[]),
  'usage': ResponseUsage(input_tokens=7036, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=734, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=7770, cost=0.05353, is_byok=False, cost_details={'upstream_inference_cost': 0.05353, 'upstream_inference_input_cost': 0.03518, 'upstream_inference_output_cost': 0.01835}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/security/session/mapper/JooqSessionMapper.java',
  'response': Response(chainOfThought=['I need to analyze this Java class for SQL antipatterns.', "Looking at the class, it's a mapper class called JooqSessionMapper that maps a jOOQ Record to a Session object.", 'Let me check for each antipattern:', "1. Poor Man's Search Engine: There are no LIKE, ILIKE, or regex operations in this code. This is just a mapper that extracts values from a Record.", "2. Implicit Columns: This mapper receives a Record and extracts specific columns from it. The mapper itself doesn't perform any query - it just maps an existing Record. The actual query that creates this Record is not shown here. The mapper explicitly accesses specific columns (SESSIONS.ID, SESSIONS.USER_AGENT, etc.), so it's not selecting all columns blindly.", "3. Beware of the Unknown: There's no query logic here that uses NULLABLE columns in conditions. This is just extracting values from a Record.", "This class is purely a mapper utility that takes an already-fetched Record and converts it to a domain object. It doesn't contain any jOOQ DSL queries or DAO interactions that would exhibit the antipatterns I'm looking for.", 'No antipatterns are present in this code.'], occurrences=[]),
  'usage': ResponseUsage(input_tokens=1350, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=289, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1639, cost=0.013975, is_byok=False, cost_details={'upstream_inference_cost': 0.013975, 'upstream_inference_input_cost': 0.00675, 'upstream_inference_output_cost': 0.007225}),
  'status': 'success'},
 {'project': 'APSfurizon/fz-backend',
  'file': '../../repositories/APSfurizon_fz-backend/application/src/main/java/net/furizon/backend/infrastructure/configuration/DatabaseConfiguration.java',

In [ ]:
Date	Slug	Usage	BYOK Usage	Requests	Prompt Tokens	Completion Tokens	Reasoning Tokens
2026-03-07 12:00:00	anthropic/claude-opus-4.5	40.862095	0	1159	5961739	442136	0