In [11]:
root_dir = ".."
analyser_path = "../../statement-counter/build/libs/statement-counter-1.0-SNAPSHOT-all.jar"

In [12]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [13]:
projects_df = pd.read_csv(f"{root_dir}/datasets/final-repositories.csv")
projects_df = projects_df.drop(columns=["response_code", "result_count", "response_code2", "result_count2"])
projects_df

                                                             name
0                                 4el1k/Spring-Api-Hibernate-JOOQ
1                                                66xc1/lazy-punch
2                                                ABCLV/ABLV_IngSW
3                                           APSfurizon/fz-backend
4                         AWS-Cloud-Community-LPU/mailing-service
5                                          AffectedArc07/ParaUtil
6                                             AisleiAvila/empresa
7                                    AkaLrz/E-commercial-Platfrom
8                                          AlexSpeal/Tracking-Bot
9                                 Alexandr-Kokorin/JavaCourse2024
10                                                    AlexzTj/p2p
11                                              AlphaFoxz/oneboot
12                                AnastasiaPleshkova/tnkf-tracker
13                              AndrewSalygin/LinkTracker-Tinkoff
14                                      Andrey582/NotificationBot
15                             Ani512/online-tutoring-app-backend
16                                       AntonioRusan/LinkTracker
17                                          Apress/beginning-jooq
18                                            Apress/pro-spring-6
19                                 AprilHan1992/fleet-spring-boot
20                                        ArcaHozota/nasb1995edv3
21                          Arden30/TinkoffJavaBackendSpring23-24
22                                             AtroposBot/Atropos
23                                                Atsushi68/trunk
24                                    Ayazkins/Java-Tinkoff-sem-2
25                                          BRP-API/brp-api-gezag
26                                        BenMAPCE/BenCloudServer
27                                 BinaryIgor/tools-and-templates
28                                         Blackdread/rest-filter
29                                        BlakieSL/SpringJOOQ_DAO
30                                        BluBluBlaBla/vidsummize
31                                          BogBond2000/Itmo_labs
32                              BorisovAlexspb/Update_tracker_bot
33                                       Bruh3509/updates-tracker
34                                      BuchnevDmitry/LinkTracker
35                                       BudgetingWebsite/Backend
36                   CaXaPCMeDoM/tinkoff-java-course-2024-backend
37                     CaptainCluster/data_intensive_assignment_3
38                               CatOrLeader/Tinkoff_Link_Tracker
39                                     ChatCode9/ChatCode-backend
40                                         Claydelas/dashboard-fx
41          D-Muscipula/tinkoff-java-backend-link-tracker-project
42                                               DanieleGotti/MED
43                                         Daniil-Vl/link-tracker
44                                Daniil4639/Tinkoff_Repository_2
45                                   DanjiTalk/danji-talk-backend
46                                              Dankoy/jforwarder
47                                        DarplexDev/darplex-java
48                                           DavidJi80/springboot
49                                             Davincii254/Stroom
50               DiSSCo/dissco-core-annotation-processing-service
51                                     DiSSCo/dissco-core-backend
52                  DiSSCo/dissco-core-digital-specimen-processor
53                                  DiSSCo/dissco-core-translator
54                            DiSSCo/dissco-data-exporter-backend
55                                           DiamondArt/Java-jooq
56                      DmitriyKosolobov/java-course-2024-backend
57                                  DrBrother/notification-system
58                                    DragomiroiuStefan/rideshare
59                                          Drewbie18/spring-rest
60                                   E1psycongr00/STUDY_REFERENCE
61                E1psycongr00/study_jooq_codegen_with_flyway_jpa
62                                              EHRoute/EHR-Route
63                                    Efler/microservice-data-bus
64                                    Efler/telegram-scrapper-bot
65                                  Eliorika/tinkoff-java-backend
66                                                Emented/webLab3
67                   EngineDevOps2/programming-todolist-fullstack
68                                  EuphoriaV/UpdateMonitoringBot
69                       FOKO-KENMOGNE-Wilfried/siggeac_prototype
70                                            FeKom/lab-ecommerce
71                                FeldmannJR/constellation-common
72                                        FeldmannJR/redstonegang
73                          Fics3/tink_java_backend_course_spring
74                   FilippoBolis/MED_Progetto_Ing_Software_23_24
75                                            FrankChen021/bithon
76                                       FrankChen021/bithon-demo
77                             GAIM-Tech-OM/killbill-ompay-plugin
78                                    Gabriele-Mazzoleni/SmarTrip
79                                           Garrettc96/cacophony
80                                     Geomatys/examind-community
81                  GeorgyDemidenkov/DemidenkovGD_Y-234_2kurs2sem
82                                     Grigalgol/vk_education_hm6
83                                           GyrosOfWar/imagehive
84                                 HSLdevcom/jore4-jore3-importer
85                                       Hamednallah/Basariat-POS
86                                         Hamednallah/Market-POS
87                                          Hellblazer/quantum-db
88                                   Hixon10/spring-boot-security
89                                          HoZanDung/ho-workflow
90                                              Hogeyama/try-java
91                                   IAGrig/link-updates-notifier
92                                  IlyaAbramovv/UpdatesAnnouncer
93                               IvanShabunin379/java-course-2024
94                                         JGMelon22/ListDemoJava
95                           JacobLewandowskiDev/GwentMMO-Backend
96                              JakeMathews/recommendation-engine
97           JixinZhang19/Online-Shopping-System-for-Black-Friday
98                              JohannesRabauer/hibernate-vs-jooq
99                                    Jominjong/mjjo-test-project
100                                        KEN3pei/oauth-hands-on
101                                          KGjertsson/macro-hub
102                                   Karthik1226/onedata_patient
103                                           Kazuuma-19/nippogen
104                             Kirill06344/TinkoffWebApplication
105                                     KirillSakira/link-tracker
106                                         KittyBot-Org/KittyBot
107                                        Knicksaas/gourmet-gate
108                                        KyleGuanDP/Assignment4
109                                       LARCH1K/LinkTracker-Bot
110                                        LalisaST/java_course_2
111                                         LeHa2505/OnThiService
112                                       LiangChenDLJ/VIPManager
113                                  LianjiaTech/bella-assistants
114                                   LianjiaTech/bella-knowledge
115                                     LianjiaTech/bella-openapi
116                                    LianjiaTech/bella-workflow
117                                  Link-Profit-System/java_mvvm
118                            LintaoAmons/java-jooq-runable-code
119                                   LogDS/SimulatorOrchestrator
120                          LucidMinded/java-course-2023-backend
121                                     M1nsong-Kim/practice-jooq
122                                       MAK-Cpp/backend-java-s2
123                            MIZINCHIK/java-course-2023-backend
124                          Macbeth-Klm/Tinkoff-java-course-2024
125                                               Maczi01/sockets
126                                   MahjongRepository/YagiMotel
127                        Malest-GmbH-Co-KG/Prog_3_Projektarbeit
128                                  MarinaBiryukova/tinkoff-java
129                                          MaroderKo/parts_shop
130                                  Mateuzz/music-website-spring
131                                        MaxZhukoff/tinkoff-bot
132                                        Missssha/Tinkofff-Back
133                                                Molzonas/EkEep
134                                MyP99999/NewsAggregatorBackend
135                                            Mykindos/BetterPvP
136                                        NaspoDev/url-shortener
137                           NastyaLush/java-course-2024-backend
138                                    Ne1loff/OnboardingPlatform
139                                 Neonik-dev/Update-Tracker-Bot
140                                    NevinTure/java-course-2024
141                                         Nick-552/link-tracker
142                         NurtilekMamashakirov/Bot-Link-Tracker
143                                           Nyrheim/PenAndPaper
144                                                    OAGi/Score
145  Online-Tutoring-Application-Team-11/backend-rest-API-service
146                                Origin-Masters/Cantine-Planner
147                            Ovoshchko/BackendTinkoffJavaSpring
148                                               PKNU-CERT-IS/BE
149                                     Pa11ady/java-link-tracker
150                            Pacan4ik/tinkoff-course-spring2023
151                                       ParadiseSS13/TaskDaemon
152                                    PathmindAI/pathmind-webapp
153                         PonomarevAlexxander/telegram-notifier
154                                   Programming-Org/Programming
155                    Prohkit/java-backend-course-2-link-tracker
156                                          ProstaOlga/prostaBot
157                                   Puru80/food-ordering-system
158                               QuantuM1o1/Tinkoff2024Homeworks
159                                                  Raha089/oops
160                                          Reazzzz/oosp-zadanya
161                                       Rohan-flutterint/texera
162                          RomanZozuliauniversity/Javacourework
163              RuslanAndrianov/Backend-Java-Tinkoff-Spring-2024
164                              RuslanHkmoff/java-backend-course
165                                     SOmegaS/financial-tracker
166                                          Saiyan1/tl-challenge
167                                        SavageSyrop/VK-courses
168                             ShaDi777/java-course-2024-backend
169                                          ShakurDmitrii/inline
170                                         SightStudio/blog-code
171                            SleepwalkerPasha/egorov_pa_project
172                               SlideHehe/java-backend-course-2
173                              SmallWorlds-Forever/sw-streaming
174                                          SoylentBob/jooq-mock
175                                     Space27/JavaBackendSpring
176                                     Stasik371/LinkTrackingBot
177                                     StubbornJava/StubbornJava
178                                               Stumpwiz/mrradb
179                                              Subtelny/DGCraft
180                               TaitoUnited/full-stack-template
181                                TerraByteDev/SkyFactionsReborn
182                                           TheLQ/forum-scraper
183                              Thee5176/SpringBoot_CQRS_Command
184                                Thee5176/SpringBoot_CQRS_Query
185                                 Thulasidharreddy/task-service
186                              Tiltuem/tinkoff-java-course-2024
187                                          TivM/Tinkoff-Project
188                                    Tosin-dotcom/notez-backend
189                                  TovarischZhukov/jooq_example
190                 TranNgocKhoa/play-framework-java-jooq-example
191                                             TunixR/HarmonyAPI
192                           UKEIAM/de.uke.iam.parkinson_on_fhir
193                               UniCodeProjects/AmusementParkDB
194                                      Unite-Organisation/Unite
195                                VadymOselskyi/airlines-booking
196                                  VictorGalkevich/LinkScrapper
197               ViktoriaGub/Object-oriented-programming-systems
198                                VladimirMorozov/orm-playground
199                                 VoroninEgor/TgBot-LinkTracker
200                                          Wani4ka/tcs-edu-task
201                               WolfOfBad/TinkoffJavaCourse2024
202                  YaroslavChetskiy/tinkoff_course_backend_part
203                                                Yer12/tastamat
204                             YuliaKrav/WebContentUpdateService
205                                         Yuno-obsessed/jodrive
206                                    ZanottiMatteo/BGTransports
207                                            ZebdaYacine/demofx
208                                            ZsgsDesign/openvsx
209                                  ZwierzchowskiM/Client-Server
210                                        aabarmin/telegram-bots
211                               aahlenst/jOOQ-mcve-json-quoting
212                                 aceton41k/java-test-framework
213                                               activej/activej
214                                       aerius/emission-service
215                             agibalov/java-library-experiments
216                                    akozitsin-hh/hh-jooq-intro
217                                          aleckbb/tracking-bot
218                                   aleksseii/TradingOperations
219                                           alexxiuccia/TrackMe
220                                    alipay/container-auto-tune
221                                            alpa011235/sandbox
222                                                   altusea/wpg
223                                           alvin-qh/study-java
224                         amalrajvinoth/jooq-optimistic-locking
225                                      anpol84/java-course-2024
226                                            anyamilichenko/soa
227                                             aplygen/j13n-saas
228                                        arhostcode/linktracker
229                          arijit98/RestaurentManagementService
230                                  arnaudroger/SimpleFlatMapper
231                                  artemius39/java-backend-2024
232                       articles-simbirsoft/JOOQ-use-in-testing
233                                        artseroff/link-tracker
234                                           atolcd/sdis-remocra
235                       atomfrede/javaland-2022-karate-workshop
236                                      auliardana/Java-orm-jooq
237                                    averbraeck/gamedata-common
238                                 averbraeck/housinggame-common
239                                          averbraeck/trustgame
240                                 averbraeck/trustgame-register
241                                   averbraeck/trustgame-scores
242                         aws-observability/aws-otel-playground
243                                                   aytdm/study
244                         badgerwithagun/async-all-the-way-down
245                             balazskrizsan/stackjudge_aws_java
246                                        beargiles/youtube-dojo
247                                               bennofs/wdumper
248               bharat-chaudhari-0302/spring-jooq-gradle-plugin
249                                        bifidok/TinkoffBackend
250                               bigseized/TinkoffCourseJava2024
251                             blueoceandevops/fleet-spring-boot
252                                        boogiespook/waltz-test
253                                             boomzin/dbservice
254                      bootique-examples/bootique-jooq-examples
255                                            borjom1/cloud-nest
256                        brianbcampbell/z_beast-product-catalog
257                                    brody-0125/The-Joy-Of-Java
258                                        bsi-software/ScoutJooq
259                                      btpka3/btpka3.github.com
260                                              buster/acmemusic
261                                       c00ler/transfer-service
262                       cardano-foundation/cardano-rosetta-java
263                                       catsloveme/telegram-bot
264                        chriswininger/ai-document-query-system
265                                         clearflask/clearflask
266                                          cn-src/snippets-java
267                                             coduction/famulex
268                         constZhur/tinkoff-backend-course-2024
269                                          cooder-org/jooq-mate
270                                      corradomio/java_projects
271                                        crate/cratedb-examples
272                                           crick77/usrbilancio
273                              crunchykillah/rest_api_springmvc
274                                         cyberpunkoff/tracktor
275                         cycastic-cumberland/libmanage-backend
276                                   danmofo/fitness-tracker-app
277                                        dbist/cockroach-docker
278                            deepakborania/revolut-backend-task
279                                             dehasi/ppp-of-ddd
280                                                derabbink/sws2
281                                 devstronomy/nasa-data-scraper
282                                    dianainya/platform-backend
283                                        diocorrea/imagewrapper
284                                               djma/play-stack
285            dndanoff/spring-boot-unit-integration-test-example
286              dominikjaniga91/system-design-interview-projects
287                                                dreamPis/oauth
288                                      dzorbey/order-scheduling
289                                       easkarov/repo-caretaker
290                           ebi-gene-expression-group/annotare2
291                                        eclipse-scout/scout.rt
292                                               eclipse/openvsx
293                                        ehrbase/migration-tool
294                                             ekgreen/star-boot
295                              ekruptsov/jooq-retrofit-crud-poc
296                                 elwin013/todoapp-multitenancy
297                                          emapfff/Link-Tracker
298                                         ericdriggs/reportcard
299                                        eterny13/url-shortener
300                             evagalyuta/services-city-discover
301                                       eziomou/library-backend

In [14]:
def get_project_dir(project: str):
    return f"{root_dir}/repositories/{project.replace("/", "_")}"

In [15]:
import os

def run_analyser(project_name):
    project_path = get_project_dir(project_name)
    # Construct the command string
    command = f"java -jar {analyser_path} {project_path}"

    try:
        # Open a pipe to the command
        with os.popen(command) as stream:
            output = stream.read().strip()
            # Return integer if output exists, otherwise None
            return int(output) if output else None
    except Exception as e:
        print(f"Error processing {project_name}: {e}")
        return None

In [16]:
projects_df["count"] = projects_df["name"].apply(run_analyser)

In [17]:
projects_df

                                                             name  count
0                                 4el1k/Spring-Api-Hibernate-JOOQ     40
1                                                66xc1/lazy-punch     22
2                                                ABCLV/ABLV_IngSW      4
3                                           APSfurizon/fz-backend    170
4                         AWS-Cloud-Community-LPU/mailing-service      4
5                                          AffectedArc07/ParaUtil      5
6                                             AisleiAvila/empresa     27
7                                    AkaLrz/E-commercial-Platfrom      7
8                                          AlexSpeal/Tracking-Bot     57
9                                 Alexandr-Kokorin/JavaCourse2024     36
10                                                    AlexzTj/p2p     16
11                                              AlphaFoxz/oneboot      6
12                                AnastasiaPleshkova/tnkf-tracker     33
13                              AndrewSalygin/LinkTracker-Tinkoff     38
14                                      Andrey582/NotificationBot     25
15                             Ani512/online-tutoring-app-backend     64
16                                       AntonioRusan/LinkTracker     53
17                                          Apress/beginning-jooq    160
18                                            Apress/pro-spring-6     71
19                                 AprilHan1992/fleet-spring-boot     98
20                                        ArcaHozota/nasb1995edv3     46
21                          Arden30/TinkoffJavaBackendSpring23-24     69
22                                             AtroposBot/Atropos     16
23                                                Atsushi68/trunk     94
24                                    Ayazkins/Java-Tinkoff-sem-2     50
25                                          BRP-API/brp-api-gezag      3
26                                        BenMAPCE/BenCloudServer    434
27                                 BinaryIgor/tools-and-templates     35
28                                         Blackdread/rest-filter     48
29                                        BlakieSL/SpringJOOQ_DAO     22
30                                        BluBluBlaBla/vidsummize      6
31                                          BogBond2000/Itmo_labs      4
32                              BorisovAlexspb/Update_tracker_bot     28
33                                       Bruh3509/updates-tracker     26
34                                      BuchnevDmitry/LinkTracker     24
35                                       BudgetingWebsite/Backend     21
36                   CaXaPCMeDoM/tinkoff-java-course-2024-backend     23
37                     CaptainCluster/data_intensive_assignment_3     27
38                               CatOrLeader/Tinkoff_Link_Tracker     62
39                                     ChatCode9/ChatCode-backend     47
40                                         Claydelas/dashboard-fx     71
41          D-Muscipula/tinkoff-java-backend-link-tracker-project     85
42                                               DanieleGotti/MED    151
43                                         Daniil-Vl/link-tracker     41
44                                Daniil4639/Tinkoff_Repository_2     47
45                                   DanjiTalk/danji-talk-backend     38
46                                              Dankoy/jforwarder     39
47                                        DarplexDev/darplex-java      5
48                                           DavidJi80/springboot      9
49                                             Davincii254/Stroom    602
50               DiSSCo/dissco-core-annotation-processing-service     38
51                                     DiSSCo/dissco-core-backend     48
52                  DiSSCo/dissco-core-digital-specimen-processor     23
53                                  DiSSCo/dissco-core-translator     30
54                            DiSSCo/dissco-data-exporter-backend     23
55                                           DiamondArt/Java-jooq      8
56                      DmitriyKosolobov/java-course-2024-backend     37
57                                  DrBrother/notification-system     34
58                                    DragomiroiuStefan/rideshare     14
59                                          Drewbie18/spring-rest      3
60                                   E1psycongr00/STUDY_REFERENCE     15
61                E1psycongr00/study_jooq_codegen_with_flyway_jpa      4
62                                              EHRoute/EHR-Route      0
63                                    Efler/microservice-data-bus     27
64                                    Efler/telegram-scrapper-bot    150
65                                  Eliorika/tinkoff-java-backend     30
66                                                Emented/webLab3      3
67                   EngineDevOps2/programming-todolist-fullstack      8
68                                  EuphoriaV/UpdateMonitoringBot     24
69                       FOKO-KENMOGNE-Wilfried/siggeac_prototype      3
70                                            FeKom/lab-ecommerce     11
71                                FeldmannJR/constellation-common      2
72                                        FeldmannJR/redstonegang    258
73                          Fics3/tink_java_backend_course_spring     76
74                   FilippoBolis/MED_Progetto_Ing_Software_23_24     91
75                                            FrankChen021/bithon    259
76                                       FrankChen021/bithon-demo      5
77                             GAIM-Tech-OM/killbill-ompay-plugin     25
78                                    Gabriele-Mazzoleni/SmarTrip     14
79                                           Garrettc96/cacophony     34
80                                     Geomatys/examind-community    575
81                  GeorgyDemidenkov/DemidenkovGD_Y-234_2kurs2sem      8
82                                     Grigalgol/vk_education_hm6     12
83                                           GyrosOfWar/imagehive     31
84                                 HSLdevcom/jore4-jore3-importer    271
85                                       Hamednallah/Basariat-POS    190
86                                         Hamednallah/Market-POS     30
87                                          Hellblazer/quantum-db     28
88                                   Hixon10/spring-boot-security      3
89                                          HoZanDung/ho-workflow     41
90                                              Hogeyama/try-java      7
91                                   IAGrig/link-updates-notifier     42
92                                  IlyaAbramovv/UpdatesAnnouncer     33
93                               IvanShabunin379/java-course-2024     44
94                                         JGMelon22/ListDemoJava      1
95                           JacobLewandowskiDev/GwentMMO-Backend      6
96                              JakeMathews/recommendation-engine      4
97           JixinZhang19/Online-Shopping-System-for-Black-Friday      7
98                              JohannesRabauer/hibernate-vs-jooq      8
99                                    Jominjong/mjjo-test-project     25
100                                        KEN3pei/oauth-hands-on     21
101                                          KGjertsson/macro-hub     91
102                                   Karthik1226/onedata_patient     26
103                                           Kazuuma-19/nippogen     40
104                             Kirill06344/TinkoffWebApplication     44
105                                     KirillSakira/link-tracker     41
106                                         KittyBot-Org/KittyBot     76
107                                        Knicksaas/gourmet-gate     40
108                                        KyleGuanDP/Assignment4      2
109                                       LARCH1K/LinkTracker-Bot     30
110                                        LalisaST/java_course_2     75
111                                         LeHa2505/OnThiService    181
112                                       LiangChenDLJ/VIPManager     21
113                                  LianjiaTech/bella-assistants    102
114                                   LianjiaTech/bella-knowledge     61
115                                     LianjiaTech/bella-openapi     87
116                                    LianjiaTech/bella-workflow    145
117                                  Link-Profit-System/java_mvvm      6
118                            LintaoAmons/java-jooq-runable-code     15
119                                   LogDS/SimulatorOrchestrator     62
120                          LucidMinded/java-course-2023-backend     38
121                                     M1nsong-Kim/practice-jooq      7
122                                       MAK-Cpp/backend-java-s2     40
123                            MIZINCHIK/java-course-2023-backend     44
124                          Macbeth-Klm/Tinkoff-java-course-2024     41
125                                               Maczi01/sockets     16
126                                   MahjongRepository/YagiMotel      6
127                        Malest-GmbH-Co-KG/Prog_3_Projektarbeit     20
128                                  MarinaBiryukova/tinkoff-java     33
129                                          MaroderKo/parts_shop     15
130                                  Mateuzz/music-website-spring      4
131                                        MaxZhukoff/tinkoff-bot     23
132                                        Missssha/Tinkofff-Back     26
133                                                Molzonas/EkEep      5
134                                MyP99999/NewsAggregatorBackend     14
135                                            Mykindos/BetterPvP    561
136                                        NaspoDev/url-shortener      5
137                           NastyaLush/java-course-2024-backend     45
138                                    Ne1loff/OnboardingPlatform     22
139                                 Neonik-dev/Update-Tracker-Bot     56
140                                    NevinTure/java-course-2024     70
141                                         Nick-552/link-tracker     36
142                         NurtilekMamashakirov/Bot-Link-Tracker     28
143                                           Nyrheim/PenAndPaper     65
144                                                    OAGi/Score   2518
145  Online-Tutoring-Application-Team-11/backend-rest-API-service     64
146                                Origin-Masters/Cantine-Planner     50
147                            Ovoshchko/BackendTinkoffJavaSpring     65
148                                               PKNU-CERT-IS/BE    895
149                                     Pa11ady/java-link-tracker     22
150                            Pacan4ik/tinkoff-course-spring2023    145
151                                       ParadiseSS13/TaskDaemon     22
152                                    PathmindAI/pathmind-webapp    159
153                         PonomarevAlexxander/telegram-notifier     31
154                                   Programming-Org/Programming     29
155                    Prohkit/java-backend-course-2-link-tracker     33
156                                          ProstaOlga/prostaBot     18
157                                   Puru80/food-ordering-system      1
158                               QuantuM1o1/Tinkoff2024Homeworks     62
159                                                  Raha089/oops      8
160                                          Reazzzz/oosp-zadanya      8
161                                       Rohan-flutterint/texera     17
162                          RomanZozuliauniversity/Javacourework     12
163              RuslanAndrianov/Backend-Java-Tinkoff-Spring-2024     43
164                              RuslanHkmoff/java-backend-course     27
165                                     SOmegaS/financial-tracker      1
166                                          Saiyan1/tl-challenge      2
167                                        SavageSyrop/VK-courses     32
168                             ShaDi777/java-course-2024-backend     36
169                                          ShakurDmitrii/inline     11
170                                         SightStudio/blog-code     34
171                            SleepwalkerPasha/egorov_pa_project     25
172                               SlideHehe/java-backend-course-2     99
173                              SmallWorlds-Forever/sw-streaming    249
174                                          SoylentBob/jooq-mock      6
175                                     Space27/JavaBackendSpring     31
176                                     Stasik371/LinkTrackingBot     27
177                                     StubbornJava/StubbornJava     15
178                                               Stumpwiz/mrradb     34
179                                              Subtelny/DGCraft     27
180                               TaitoUnited/full-stack-template      3
181                                TerraByteDev/SkyFactionsReborn    129
182                                           TheLQ/forum-scraper     25
183                              Thee5176/SpringBoot_CQRS_Command     19
184                                Thee5176/SpringBoot_CQRS_Query     16
185                                 Thulasidharreddy/task-service      9
186                              Tiltuem/tinkoff-java-course-2024     42
187                                          TivM/Tinkoff-Project     31
188                                    Tosin-dotcom/notez-backend     11
189                                  TovarischZhukov/jooq_example     23
190                 TranNgocKhoa/play-framework-java-jooq-example     15
191                                             TunixR/HarmonyAPI    150
192                           UKEIAM/de.uke.iam.parkinson_on_fhir     21
193                               UniCodeProjects/AmusementParkDB    249
194                                      Unite-Organisation/Unite     65
195                                VadymOselskyi/airlines-booking     14
196                                  VictorGalkevich/LinkScrapper     39
197               ViktoriaGub/Object-oriented-programming-systems      8
198                                VladimirMorozov/orm-playground     12
199                                 VoroninEgor/TgBot-LinkTracker     29
200                                          Wani4ka/tcs-edu-task     28
201                               WolfOfBad/TinkoffJavaCourse2024     33
202                  YaroslavChetskiy/tinkoff_course_backend_part     38
203                                                Yer12/tastamat     43
204                             YuliaKrav/WebContentUpdateService     20
205                                         Yuno-obsessed/jodrive     98
206                                    ZanottiMatteo/BGTransports     95
207                                            ZebdaYacine/demofx      6
208                                            ZsgsDesign/openvsx     27
209                                  ZwierzchowskiM/Client-Server     10
210                                        aabarmin/telegram-bots     22
211                               aahlenst/jOOQ-mcve-json-quoting     41
212                                 aceton41k/java-test-framework      9
213                                               activej/activej     77
214                                       aerius/emission-service     25
215                             agibalov/java-library-experiments     19
216                                    akozitsin-hh/hh-jooq-intro      3
217                                          aleckbb/tracking-bot     35
218                                   aleksseii/TradingOperations     41
219                                           alexxiuccia/TrackMe      6
220                                    alipay/container-auto-tune    181
221                                            alpa011235/sandbox     28
222                                                   altusea/wpg      8
223                                           alvin-qh/study-java     80
224                         amalrajvinoth/jooq-optimistic-locking      4
225                                      anpol84/java-course-2024     33
226                                            anyamilichenko/soa     23
227                                             aplygen/j13n-saas     33
228                                        arhostcode/linktracker     47
229                          arijit98/RestaurentManagementService      8
230                                  arnaudroger/SimpleFlatMapper     83
231                                  artemius39/java-backend-2024     92
232                       articles-simbirsoft/JOOQ-use-in-testing      3
233                                        artseroff/link-tracker     25
234                                           atolcd/sdis-remocra    499
235                       atomfrede/javaland-2022-karate-workshop      7
236                                      auliardana/Java-orm-jooq      2
237                                    averbraeck/gamedata-common     41
238                                 averbraeck/housinggame-common     20
239                                          averbraeck/trustgame     30
240                                 averbraeck/trustgame-register      8
241                                   averbraeck/trustgame-scores     28
242                         aws-observability/aws-otel-playground      1
243                                                   aytdm/study      2
244                         badgerwithagun/async-all-the-way-down      2
245                             balazskrizsan/stackjudge_aws_java      1
246                                        beargiles/youtube-dojo     51
247                                               bennofs/wdumper     40
248               bharat-chaudhari-0302/spring-jooq-gradle-plugin      1
249                                        bifidok/TinkoffBackend     79
250                               bigseized/TinkoffCourseJava2024     31
251                             blueoceandevops/fleet-spring-boot     65
252                                        boogiespook/waltz-test    739
253                                             boomzin/dbservice     39
254                      bootique-examples/bootique-jooq-examples      1
255                                            borjom1/cloud-nest     53
256                        brianbcampbell/z_beast-product-catalog      1
257                                    brody-0125/The-Joy-Of-Java      3
258                                        bsi-software/ScoutJooq     29
259                                      btpka3/btpka3.github.com     83
260                                              buster/acmemusic     17
261                                       c00ler/transfer-service      6
262                       cardano-foundation/cardano-rosetta-java     40
263                                       catsloveme/telegram-bot     22
264                        chriswininger/ai-document-query-system      4
265                                         clearflask/clearflask     87
266                                          cn-src/snippets-java      4
267                                             coduction/famulex      7
268                         constZhur/tinkoff-backend-course-2024     27
269                                          cooder-org/jooq-mate      0
270                                      corradomio/java_projects    321
271                                        crate/cratedb-examples      7

In [18]:
projects_df.to_csv('../datasets/project-statement-counts.csv', index=False)